# Dockerfile
# Start from a Python 3 Image 
FROM --platform=linux/amd64  python:3.10 as builder

# Change current directory to /app
WORKDIR /server

# Copy application code to server/
COPY . /server

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN apt-get update && apt-get install -y wget curl gnupg
RUN pip install playwright && playwright install --with-deps

# debconf to be non-interactive
ENV DEBIAN_FRONTEND noninteractive

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "-w", "1", "--threads", "4", "app:app"]