name: Fly Deploy
on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    name: Run server tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt1-dev

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest

  deploy:
    name: Deploy app
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd server/ && flyctl deploy --remote-only
